bindAddr = "0.0.0.0"  
bindPort = 14000
kcpBindPort = 14001

auth.method = "token"
auth.token = "nn69JtgT00JrVC5t"

transport.maxPoolCount = 2000
transport.tcpMux = true
transport.tcpMuxKeepaliveInterval = 60
transport.tcpKeepalive = 7200
transport.tls.force = false

webServer.addr = "0.0.0.0"
webServer.port = 14002
webServer.user = "o7NYiTX8"
webServer.password = "ZtksIAUDlMnzBXjV"
dashboardPwd = "ZtksIAUDlMnzBXjV"

vhostHTTPPort = 14003
vhostHTTPSPort = 14004
log.file = "/var/log/frps.log"
log.level = "info"
log.maxDays = 30


maxPoolCount = 50
tcpmuxHTTPConnectPort  = 14005

allowPorts = [
    { start = 10000, end = 13999 }, 
    { start = 14006, end = 60000 }, 
]
